services:
  dev-yahtzee-backend:
    build:
      context: ./server # Path to the backend folder
      dockerfile: Dockerfile # Dockerfile inside the backend folder
    ports:
      - "3001:3001"
    #    volumes:
    #      - ./backend/wwwroot:/app/dist
    volumes:
      - ./server:/app # Mount the frontend code directory into the container
    #  - /app/node_modules # Prevent overwriting node_modules in container with local version
  dev-yahtzee-frontend:
    build:
      context: ./client # Path to the backend folder
      dockerfile: Dockerfile # Dockerfile inside the backend folder
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
    command: npm start
